### ISSUE TITLE
😮 WOW! 

### ISSUE THREAD

**Issue by ahmadawais** [gruns/irondb#14]
I have created this issue to thank the author, feel free to close it once read.

I am always researching good readme documentation as I am a fan of making things [concise and useful](https://github.com/ahmadawais/create-guten-block) — while reading the `READMe.md` file on this project I am in awe! Seriously, the lingo used is concise and extremely helpful in explaining each topic discussed therein.

Mad props! Peace! ✌️

**Comment by gruns** [comment]
Thank you for your feedback and kind words, Ahmad. Sincerely.

Don't hesitate to let me know if there's anything I can do for you.
